### ISSUE TITLE
Create v0.3.0 release

### ISSUE THREAD

**Issue by xaur** [decred/dcrlnd#131]
README links to [installation instructions](https://github.com/decred/dcrlnd/blob/master/docs/INSTALL.md) and those link to [releases](https://github.com/decred/dcrlnd/releases) page, and that has the latest proper release for v0.2.1 while the latest is v0.3.0.

I don't know how people commonly install dcrlnd but if there's a chance they use the Releases page, it might help them to navigate faster if they see a proper GH release.

As discussed in #dev around Jan 25 during the release days, maintaining GH releases involves extra not fun work of manually preparing the markdown release notes (because Release pages use a different Markdown renderer, for whatever reason). If that is too much effort, at least linking to [v0.3 release notes](https://github.com/decred/dcrlnd/blob/master/docs/release-notes/release-notes-0.3.0.md) would still be an improvement in navigation.

**Comment by matheusd** [comment]
Published the release. Download link is set to the v1.6.0 archive: https://github.com/decred/dcrlnd/releases/tag/v0.3.0

**Comment by xaur** [comment]
Great, thanks! Feel free to close is there's nothing more to do for this issue.
