### ISSUE TITLE
Update `docker/README.md` - currently it leads to an error

### ISSUE THREAD

**Issue by vinnyTechnic** [decred/dcrlnd#135]
### Background

I tried to go through `docker/README.md` today and came across this issue

### Your environment

* Version of `dcrlnd`
master
* Which operating system (`uname -a` on *Nix).
linux
* Version of `dcrd` or other backend.
Dockerfile pinned 1.5.1

### Steps to reproduce

`docker-compose run -d --name alice dcrlnd` :

```
2021-03-07 18:19:19.683 [DBG] DCRW: Starting rpc syncer
2021-03-07 18:19:19.732 [INF] DCRW: Headers synced through block 6bef82c645999585f7255cb02672921ac2f5492820090cd635fe3a59d16b4f87 height 0
2021-03-07 18:19:19.732 [INF] DCRW: Transactions synced through block 6bef82c645999585f7255cb02672921ac2f5492820090cd635fe3a59d16b4f87 height 0
2021-03-07 18:19:19.733 [ERR] DCRW: RPCSyncer error: rpcsyncer.Run:
        dcrd.GetMempoolTSpends: Invalid transaction type: tspend -- supported types: [regular tickets votes revocations all]            
```

### Expected behaviour

Maybe the dcrlnd version should be pinned to a tag without TSPEND or the dcrd/dcrwallet Dockerfiles should be updated to 1..6.1. I'm unsure if this should wait until the TSPEND fork happens

**Comment by vinnyTechnic** [comment]
When trying to update to 1.6.1 myself, https://github.com/decred/dcrlnd/blob/a275ed61324ed9ef31ebe801b0c7f3dc5ef57be9/docker/dcrd/Dockerfile#L35-L37 was problematic

**Comment by matheusd** [comment]
The docker tests runs in simnet (which already supports tspends), so the correct course of action is to update the docker scripts to 1.6.x.

**Comment by jrick** [comment]
gencerts got a complete rewrite for 1.6 with new flags.  the equivalent of that old command would be:

`gencerts -L -H dcrd -H dcrwallet -f /config/rpc.{cert,key}`
