### ISSUE TITLE
 Update all CLI flags to remove the namespacing

### ISSUE THREAD

**Issue by matheusd** [decred/dcrlnd#14]
Originally at https://github.com/davecgh/dcrlnd/issues/1

**Comment by fguisso** [comment]
At this point we have just decreds namespacing, this issue still required?

List of actual namespacing:
|--decred|*chianConfig|
|--dcrd|*dcrdConfig|
|--dcrwallet|*dcrwalletConfig|
|--autopilot|*autoPilotConfig|
|--tor|*torConfig|
|--hold|*hold.Config|
|--routing|*routing.Config|
|--workers|*lncfg.Workers|
|--caches|*lncfg.Caches|
|--prometheus|lncfg.Prometeus|
|--wtclient|*lncfg.WtClient|
|--watchtower|*lncfg.WatchTower|
|--legacyprotocol|*lncfg.LegacyProtocol|

and all SubRPCServerConfigs: `--signrpc`, `--walletrpc`, `--autopilotrpc`, `--chainrpc`, `--invoicesrpc`, `--routerrpc`, `--watchtowerrpc`, `--wtclientrpc`

**Comment by matheusd** [comment]
This was mainly aimed at removing the `decred.*`  namespace config switches (given we're always on just the decred network). The other ones are relevant (dcrd/dcrwallet are legitimately used for different things).
