### ISSUE TITLE
Lightning Network-based SaaS platform apps for enterprise?

### ISSUE THREAD

**Issue by Shane-Neblio** [decred/dcrlnd#164]
Issue?  We need to keep up with Bitcoin's steps into adoption. 
Centralized money is pushing it onto enterprise. Now it's Lightning will be getting SaaS support it seems. 
https://twitter.com/saylor/status/1575922586307133441

![image](https://user-images.githubusercontent.com/95306637/193435503-54a31931-1a40-4177-895a-ef89af28eddc.png)

I don't know about others but I just wanted to say, I would vote Yes for a heavily funded proposal that got our Lightning to also have a suite of apps for enterprise like Microstrategy is getting on SaaS.

Just saying.

**Comment by Shane-Neblio** [comment]
If bitcoin can do it. decred can do it too.

**Comment by matheusd** [comment]
This is not an issue relevant to the dcrlnd repo. If you have a specific idea or proposal in mind, please discuss it [in matrix](https://matrix.to/#/#proposals:decred.org) or on the [proposals](https://proposals.decred.org/) website.
