### ISSUE TITLE
Hitting unused Address gap limit

### ISSUE THREAD

**Issue by alexlyp** [decred/dcrlnd#169]
### Background

Through just normal usage, I have hit dcrlnwallet's gap limit, but not sure how to remove that limitation to open new channels or close existing channels.

### Your environment

* Version of `dcrlnd`.
  0.3.7
* Which operating system (`uname -a` on *Nix).
  Fedora 34
* Version of `dcrd` or other backend.
  1.7.5
* Any other relevant environment details.

### Steps to reproduce
Not sure exactly how to reproduce, but basically just normal usage.  Created some deposit addresses, opened and closed some channels.  But now whenever I attempt to do any of that I get the gap limit error.

**Comment by matheusd** [comment]
Looks to be an issue with not using the correct mode for wrapping addresses (iirc we saw that once in decrediton, when dcrwallet changed the default mode from wrapping to error). Will look into fixing it.
