### ISSUE TITLE
Add piperx/pipetx

### ISSUE THREAD

**Issue by matheusd** [decred/dcrlnd#55]
Similar to dcrwallet.

piperx is used to shutdown the daemon when the wallet is closed and pipetx allows binding the rpc server in a random port and informing the caller of this port, which in turn allows multiple dcrlnd instances running in the same machine.

**Comment by githubsands** [comment]
I can take this on if you haven't started yet @matheusd

**Comment by matheusd** [comment]
Sure

**Comment by matheusd** [comment]
Hey @githubsands are you still looking to work on this? Otherwise I'll pass this along.

**Comment by matheusd** [comment]
Closed by #117
