### ISSUE TITLE
Remove `--mainnet`: it should be the default network

### ISSUE THREAD

**Issue by matheusd** [decred/dcrlnd#70]
This is to keep dcrlnd in line with other decred tools where by default mainnet is used unless `--testnet` or `--simnet` is specified.

**Comment by termoose** [comment]
Hopefully PR #72 solves this and the tightly connected issue #71. I added `regtest` as an option as well, if this is not needed or wanted I can remove it in the PR! Let me know if you see any issues!

**Comment by matheusd** [comment]
Closed via #72
