### ISSUE TITLE
Config build tags to build subsytems by default

### ISSUE THREAD

**Issue by matheusd** [decred/dcrlnd#76]
Most subsystems are meant to be built in the final production build but aren't currently due to use of build tags.

Upstream this is solved by producing release builds via `make` but we don't want to rely on that given our preferred [build tool](https://github.com/jrick/release).

So we should switch build tags from positive (e.g. `routerrpc`) to negative (`!routerrpc`) so that by default the desired subsystems are included in a release build and you don't need anything other than `go build' to get a full fledged dcrlnd node.

**Comment by matheusd** [comment]
We might wanna consider whether to include `walletrpc` by default at this moment though, since dcrwallet has a better and more complete grpc server.

**Comment by fguisso** [comment]
Working on it

**Comment by fguisso** [comment]
done in #77
